### PR TITLE
Romanian tvrplus.json added

### PR DESCRIPTION
**Pull request by karlo2105**
Romanian PBS consisting of following channels : 

1. TVR 1 
2. TVR HD 
3. TVR 2 
4. TVR 3 
5. TVR International
6. TVR Cluj
7. TVR Craiova
8. TVR Iasi
9. TVR Targu Mures
10. TVR Timisoara

Notice : Unlike stated in its name, TVR HD is broadcasted only in 480p. TVR Moldova source is not found ate the moment.

### CODE REVIEW

**Comment by beardypig** [comment]
Awesome work @karlo2105, as usual :D

**Comment by karlo2105** [comment]
You are welcome. ;)
Is there any chance to split log by branch ?

**Comment by beardypig** [comment]
I'm not sure, I don't really use the github web interface much, only for merging pull requests. 

The best way is to use the git command line interface, I don't know if [GitHub Desktop](https://desktop.github.com/) would work too...

**Comment by karlo2105** [comment]
Thanks for tip. ;)

**Pull request merged**
