### PR TITLE
add mediaklikk.json

### PR DESCRIPTION
**Pull request by karlo2105**
Mediaklikk channels : 

- M1
- M2
- M4
- M5
- Duna
- Duna World

### CODE REVIEW

**Comment by beardypig** [comment]
Thanks @karlo2105! 

Do you think you can update your fork so that all the previous commits are not included in future PRs?

**Comment by karlo2105** [comment]
How to do it?

**Comment by beardypig** [comment]
If you are just using the web interface: https://www.sitepoint.com/quick-tip-sync-your-fork-with-the-original-without-the-cli/

If you are using the command line: https://help.github.com/articles/syncing-a-fork/

:)

**Comment by karlo2105** [comment]
Thanks for tip i think i finally made it.

**Comment by beardypig** [comment]
Cool :-) Your next PR will look cleaner in the interface :-)

**Pull request merged**
