### PR TITLE
Bringing fork up to date

### PR DESCRIPTION
**Pull request by karlo2105**

### CODE REVIEW

**Comment by karlo2105** [comment]
Is it ok now?

**Comment by beardypig** [comment]
Wrong way round, you gotta merge my repo in to your fork :-)

**Comment by karlo2105** [comment]
Is it good on picture : http://imgur.com/a/UvhWg
I use github as a active user for the first time. I thought it was easier. But I finally succeeded.

**Comment by karlo2105** [comment]
Ok i think i managed it.

**Pull request closed without merging**
