### PR TITLE
added nrk.json

### PR DESCRIPTION
**Pull request by karlo2105**
Norwegian public service NRK channels : 

- NRK 1
- NRK 2
- NRK 3
- NRK Super

### CODE REVIEW

**Comment by karlo2105** [comment]
@beardypig 
Could you explain me how to pull single request one by one instead of general pull request which sends everything at once ?

**Comment by beardypig** [comment]
I'm not really sure, I hardly use the Github interface. I do everything via the command line on linux. There is a Windows desktop client for github that might make it easier for you: https://desktop.github.com/

**Comment by karlo2105** [comment]
I think I figured it out. To split PR, I need to create branches for every json datafile.

**Comment by beardypig** [comment]
Cool, that'll do it! :)

**Comment by beardypig** [comment]
Will you move this one into a new branch?

**Comment by karlo2105** [comment]
Yes from now I will push requests through single branches.

**Comment by karlo2105** [comment]
It's too complicated to move existing datafiles to new branch, so you can merge it. 
I will try with newly created files.

**Comment by beardypig** [comment]
OK, cool :)

**Pull request merged**
